# This is a basic workflow to help you get started with Actions

name: TestOpenSrc

on:

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  opensrc:
    
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: CHECKOUT ONTARIOVERIFY 
        uses: actions/checkout@v2
        env:
          PAT: ${{ secrets.token }}
        with:
          repository: ongov/OntarioVerify
          ref: refs/heads/main
          token: $PAT
      - name: LS CHECK
        run: ls -al
