# This is a basic workflow to help you get started with Actions

name: TestOpenSrc
on:
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  opensrc:
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.PAT }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: CONFIG ENV
        run: |
          echo "https://sanchilon:$PAT@github.com" > $HOME/.git-credentials
          git config --global credential.helper 'store --file $HOME/.git-credentials'
          git config --global user.name "sanchilon" && git config --global user.email "sandeep.chiluveru@ontario.ca" 
      - name: ECHO
        run: |
          echo $GITHUB_ACTOR
          echo $PAT
          cat $HOME/.git-credentials 
      - name: INIT
        run: |
          git clone https://github.com/ongov/OpenVerify
          cd OpenVerify && git switch -C main origin/main && git pull --rebase origin main
          ls -al    
     # - name: CHECKOUT ONTARIOVERIFY 
     #   uses: actions/checkout@v2
     #   with:
     #     repository: ongov/OpenVerify
     #     ref: refs/heads/main
     #     token: $PAT
      - name: LS CHECK
        run: ls -al
