name: OpenSrc
on:
  workflow_dispatch:
jobs:
  opensrc:
    runs-on: ubuntu-latest
    environment: WF_Env
    steps:
      - id: init
        name: INIT
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          echo "$PAT" > "$HOME/.secret"
          echo "$HOME/.secret"
      - name: SET_CONFIG
        run: |
          echo ${{ steps.init.env.PAT }}
          git config --global user.name "sanchilon" && git config --global user.email "sandeep.chiluveru@ontario.ca"
          git config --global credential.https://github.com.username "sanchilon" 
          git config --global credential.helper '!f() { test \"$1\" = get && echo \"password=$(cat $HOME/.secret)\"; }; f'
      - name: INIT
        run: |
          git clone https://github.com/ongov/OntarioVerify
          cd OntarioVerify && git switch -C main origin/main && git pull --rebase origin main
          ls -al
