name: OpenSrc
on:
  workflow_dispatch:
jobs:
  opensrc:
    runs-on: ubuntu-latest
    steps:
      - name: INIT
        run: |
          mkdir OntarioVerify && cd OntarioVerify
          git init
          git config --global user.name "sanchilon" && git config --global user.email "sandeep.chiluveru@ontario.ca"
          git remote add origin https://github.com/sanchilon/VerifyOpenSource
          git branch -m main
          git pull origin main
          ls -al
      
