name: OpenSrc
on:
  workflow_dispatch:
jobs:
  opensrc:
    runs-on: ubuntu-latest
    steps:
      - id: init
        name: INIT
        env:
          PAT: ${{ secrets.PAT }}
          UID: ${{ environment.USERNAME }}
        run: |
          echo ${{ env.UID }}
          mkdir OntarioVerify && cd OntarioVerify
          git init
          git config --global user.name "sanchilon" && git config --global user.email "sandeep.chiluveru@ontario.ca"
          git config credential.helper '!f() { printf "%s\n" "username=sanchilon" "password=${{env.PAT}}"; };f'
          git remote add origin https://github.com/sanchilon/VerifyOpenSource
          git branch -m main
          git pull origin main
          ls -al
      
