name: CreateOpenSrc
on: 
  workflow_dispatch:
jobs:
  opensrc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: WF_Env
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      -uses: actions/checkout@v2
       with:
         repository: sanchilon/VerifyProj
         path: ./a
         ref: refs/heads/main
         token: ${{ secrets.PAT }}
      - uses: actions/checkout@v2
        with:
          repository: ongov/OntarioVerify
          ref: refs/heads/main
          token: ${{ secrets.PAT }}
   
   
