name: OpenSrc
on:
  workflow_dispatch:
jobs:
  opensrc:
    runs-on: ubuntu-latest
    environment: WF_Env
    steps:
      - id: init
        name: INIT
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          mkdir OntarioVerify && cd OntarioVerify
          echo "$PAT" > "$HOME/.secret"
          git init
          git config --global user.name "sanchilon" && git config --global user.email "sandeep.chiluveru@ontario.ca"
          git config --global init.defaultBranch main
          git config --global crential.https://github.com/ongov/OntarioVerify.git.username "sanchilon" 
          git config --global credential.helper '!f() { test \"$1\" = get && echo \"password=$(cat $HOME/.secret)\"; }; f'
          git remote add origin https://github.com/ongov/OntarioVerify
          git switch -C main origin/main
          git pull origin main
          ls -al
      
