name: OpenSrc
on:
  workflow_dispatch:
jobs:
  opensrc:
    runs-on: ubuntu-latest
    environment: WF_Env
    steps:
      - id: init
        name: INIT
        env:
          PAT: ${{ secrets.PAT }}
        run: echo "https://sanchilon:$PAT@github.com" > $HOME/.git-credentials
      - name: ECHO
        run: cat $HOME/.git-credentials
      - name: SET_CONFIG
        run: |
          git config --global user.name "sanchilon" && git config --global user.email "sandeep.chiluveru@ontario.ca"
          git config --global credential.helper 'store --file $HOME/.git-credentials'
      - name: INIT
        run: |
          git clone https://github.com/ongov/OpenVerify
          cd OpenVerify && git switch -C main origin/main && git pull --rebase origin main
          ls -al
