name: OpenSrc
on:
  workflow_dispatch:
jobs:
  opensrc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: sanchilon/VerifyProj
          path: ./VerifyProj
          ref: refs/heads/main
          token: ${{ secrets.PAT }}
      - name: Checkout OntarioVerify
        uses: actions/checkout@v2
        with:
          repository: ongov/OntarioVerify
          path: ./OpenVerify
          ref: refs/heads/main
          token: ${{ secrets.PAT }}
      - name: LIST
        run: ls -al ./VerifyOpenSource && ls -al ./OpenVerify
     
