name: OpenSrc
on:
  workflow_dispatch:
jobs:
  opensrc:
    runs-on: ubuntu-latest
    steps:
      - name: LIST
        run: ls -al 
      - name: CHECKOUT_LOCAL
        uses: actions/checkout@v2
        with:
          repository: sanchilon/VerifyOpenSource
          path: ./a
          ref: refs/heads/main
          token: ${{ secrets.PAT }}
      
