name: WF_OpnSrc
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  opnsrc_wf:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.PAT }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: ongov/OntarioVerify
          ref: refs/heads/main
          token: $PAT
  
